KeepSafe/dexcount-gradle-plugin

README.md, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountExtension.groovy, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
With this functionality we could easily use for instance the [Jenkins Plot Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Plot+Plugin) to see for each build how many methods / fields were added / removed.
=> Add CSV export functionality

src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
While testing out the SNAPSHOT with the exportAsCSV functionality, I saw that the output was printed onto the terminal and not into the file.
This should fix it. I'm sorry for the inconveniences.
=> Fix minor bug in exportAsCSV (output was not written to file)

src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
When proguard is enabled with `-dontobfuscate`, the variant will have a non-null mapping file object, but no mapping file will be written.  Previously we treated this as a strange failure, but apparently it is a normal condition.
=> Reduce non-existing mapping file statement to DEBUG

CHANGELOG.md, README.md, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountExtension.groovy, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
I'm unhappy with the proliferation of config options.  None of them (except `includeClassNames`, `printAsTree`, and `verbose`) are particularly useful, especially `exportAsCSV`.  The file it generates, however, is unquestionably useful.  We've had several user issues where summary counts were needed, and having a dedicated output file is far better than handing out awk snippets.
So - we kill the config knob and make the API simpler, and retain the useful part.  Along with that, the plugin task is cleaned up quite a bit as well.
=> Remove `exportAsCSV`, print the summary every time

src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
when execute task count**DexMethods. Thought dex methods
can be seen in console output. But there's an exception like
"Property 'apkOrDex' with value 'com.android.build.gradle.internal.api.ApkVariantOutputImpl_Decorated@1f61ab4' cannot be serialized."
=> fix error apkOrDex can't be serialized.

CHANGELOG.md, README.md, gradle.properties, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy, src/main/groovy/com/getkeepsafe/dexcount/OutputFormat.groovy
=> Revert #32, remove `@Input` annotation, add diagnostics

src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
when I see the total method count output for my project, I don't find it super helpful because it is just a number. I want to see how much of the total 65,536 method count my project is taking up.
=> Add percentage of total methods project is taking up to output.

src/main/groovy/com/getkeepsafe/dexcount/PackageTree.groovy
Fixes #12
This regressed when I added default-value parameters to PackageTree;
this compiles to an unholy horror of pass-args-by-global-static
dynamicism and other unspeakables, including the verifier crash.
This PR removes default parameters, restoring order to PackageTree
once again.
=> Fix ctor-call-within-branch failure on buggy JVMs, again

src/main/groovy/com/getkeepsafe/dexcount/DexCountException.groovy, src/main/groovy/com/getkeepsafe/dexcount/DexFile.groovy, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
We shouldn't cause build failures when dexcount fails.
This PR catches and logs exceptions, but doesn't fail the build.  Fixes #83.
=> Don't crash when parsing dex data fails

src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
It currently has `@OutputFile`, which can cause Gradle to barf if the
dir already exists.
Fixes #84.
=> 'chartDir', as a directory, should have `@OutputDirectory`

src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy
Per #96, we have been misusing the Gradle API.  This commit uses the
task-ordering APIs to a) require that assemble runs before dexcount, and
b) ensure that running assemble triggers dexcount.
Fixes #96
=> Dedupe task invocations

src/main/groovy/com/getkeepsafe/dexcount/DexFile.groovy
Process.waitFor(long, TimeUnit) was added to Java 8. Achieve the same by
just Thread.sleep()-ing for some time and check if the process is still
alive.
=> Support Java 7

build.gradle, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountExtension.groovy, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
This will cut time-to-resolution on a good number of Github issues,
many of which result from running an outdated plugin version.
=> Print plugin name and version when invoked with '--stacktrace'

gradle/wrapper/gradle-wrapper.properties, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy, src/main/groovy/com/getkeepsafe/dexcount/GradleApi.groovy
Gradle 2.14 repackaged the ShowStacktrace enum, breaking us at the
apply stage.  It is still an enum and still has the same constants, so
we can access it dynamically and match on its `name()`.
Fixes #109.
=> Remove direct references to ShowStacktrace

src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy
Android build tools are starting to be compiled with JDK 8, which means
that when invoking external tools (e.g. `dx` for counting .aar files),
we can't guarantee that we won't crash with a version-mismatch error.
Since the state of these tools is beyond our control, we may as well
strongly urge people to move to Java 8 for building.  At the very
least we need to disclaim responsibility if they don't, and that's what
this commit does.
Fixes #118.
=> Warn if Gradle is being run on Java 7 or below.

.buildscript/test.sh, integration/app/build.gradle, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountExtension.groovy, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
This commit adds a config option providing a measure of customizability
to TeamCity statistic names, useful for projects with more than one APK
whose counts are tracked.
```gradle
dexcount {
teamCitySlug = 'YourStringHere' // or project.name, etc
}
```
This slug defaults to null.  If given, it is inserted into the TeamCity
statistic key just after 'DexCount', e.g.
`DexCount_YourStringHere_debug_MethodCount`.
Fixes #128
=> Add configurable slug for TeamCity statistics

src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
As it turns out, tasks with outputs but no inputs are considered by
Gradle to be up-to-date based on the outputs alone, meaning that you
can build, change your code, then rebuild, and not see updated counts.
This change removes the output annotations, fixing the staleness
problem - but also, opting out of Gradle's incremental builds entirely.
Fixes #131.
=> Remove output annotations to opt out of Gradle caching

README.md, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountExtension.groovy, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy
This PR adds a new option `runOnEachAssemble` to `dexcount` to allow `assemble` tasks to run without the `countDebugDexMethods` and `countReleaseDexMethods`.
Closes #125
=> Add runOnEachAssemble option to prevent task from running after assemble

src/main/groovy/com/getkeepsafe/dexcount/sdkresolver/SdkResolver.groovy
Including ndk_dir path into generated local.properties file, if it's available in environment variable ANDROID_NDK_HOME 
Fix for #144
=> Including ndk_dir path into generated local.properties file

.buildscript/test.sh, build.gradle, gradle/wrapper/gradle-wrapper.properties, integration/build.gradle, integration/gradle/wrapper/gradle-wrapper.properties, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountExtensionSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountPluginSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/InstantRunSpec.groovy
Instead of grabbing variant output from the `assemble` task, we can hook up to the `package` task and depend on that.
The wrinkle is that, in the new tools version, its output is a directory, as opposed to the prior version that yielded a single package file.  The counter task is a little more complicated now, but things seem to work.  Fingers crossed.
Fixes #161
=> Support Android Gradle Plugin 3.0.0+

src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountExtensionSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountPluginSpec.groovy
This large refactor centralizes the hitherto ad-hoc job of supporting multiple versions of the Android Gradle plugin, in the process re-enabling counts for AAR projects.
The core logic of instantiating and registering dexcount tasks moves into an abstract `Provider` class, which has legacy and 3.0+ implementations.
Fixes #174
=> Refactor for AAR support

build.gradle
This will let user projects define the plugin version they want; should
be compatible from version 2.X on through 3.0+.
Fixes #169
=> Make Android Gradle plugin a compile-only dependency

gradle/wrapper/gradle-wrapper.properties, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountExtensionSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountPluginSpec.groovy
This commit refactors the task into an abstract base and two concrete
implementations, one for AGP 2 and one for AGP 3.  This removes the
dual-optional-input model.  The legacy task is _not_ incremental, and
just holds a reference to the BaseVariantOutput, the way it used to.
The modern task remains incremental.
Fixes #181
=> Refactor to support renamed variant outputs

src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy
We really ought to re-write this plugin in Kotlin.
Fixes #187
=> Fix typo that only Groovy would ever allow

build.gradle, gradle/versions.gradle, integration/app/build.gradle, integration/build.gradle, integration/tests/build.gradle
PR: https://github.com/KeepSafe/dexcount-gradle-plugin/pull/193 must be merged first
=> [Gradle] - Use versions.gradle to organize dependencies

gradle/compile.gradle
Silencing Java warnings since out main source sets are in Groovy and Kotlin(soon to be just Kotlin).
```
$ gradlew test
> Task :compileKotlin
Using kotlin incremental compilation
> Task :compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
```
=> [Gradle] - Add Javadoc support back in, turn off Java warnings

.buildscript/test.sh, build.gradle, src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
Closes #127
Basically I am using the re-packaged API and then followed this PR https://github.com/KeepSafe/dexcount-gradle-plugin/pull/126 in order to add it back in.
Example:
=> [Logging] - Add color logging back in

src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy, src/main/kotlin/com/getkeepsafe/dexcount/ColorConsole.kt
This lets us provide colored console output to older versions of Gradle, and provides us the means to do so for future versions if/when StyledTextOutput is repackaged again.
Verified manually by reverting the integration test project to Gradle 2.14 and examining the output; I'm not at all sure how to test this in an automated fashion.
=> Use StyledTextOutput via reflection

src/main/kotlin/com/getkeepsafe/dexcount/Deobfuscator.kt, src/main/kotlin/com/getkeepsafe/dexcount/GradleApi.kt, src/main/kotlin/com/getkeepsafe/dexcount/IOUtil.kt, src/main/kotlin/com/getkeepsafe/dexcount/PackageTree.kt, src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt, src/test/groovy/com/getkeepsafe/dexcount/DexFileSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountExtensionSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountPluginSpec.groovy
- Remove vestiges of Groovy code, especially IOUtil.
- Consolidate Gradle API extensions into GradleApi.kt
- Use `null` less
=> Bits of Kotlin-related cleanup

src/main/kotlin/com/getkeepsafe/dexcount/PackageTree.kt
Attempting to fix the following:
**Kotlin:**
```
w: /home/travis/build/KeepSafe/dexcount-gradle-plugin/src/main/kotlin/com/getkeepsafe/dexcount/PackageTree.kt: (139, 13): 'when' is exhaustive so 'else' is redundant here
w: /home/travis/build/KeepSafe/dexcount-gradle-plugin/src/main/kotlin/com/getkeepsafe/dexcount/Tasks.kt: (22, 23): 'Nullable' is deprecated. Deprecated in Java
w: /home/travis/build/KeepSafe/dexcount-gradle-plugin/src/main/kotlin/com/getkeepsafe/dexcount/Tasks.kt: (70, 6): 'Nullable' is deprecated. Deprecated in Java
```
=> Fix warnings from kotlin

.buildscript/test.sh, gradle/versions.gradle, integration/gradle/wrapper/gradle-wrapper.properties, integration/lib/build.gradle, integration/lib/src/main/AndroidManifest.xml, integration/lib/src/main/java/com/getkeepsafe/dexcount/integration/Lib.java, integration/settings.gradle, src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt, src/main/kotlin/com/getkeepsafe/dexcount/Tasks.kt, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountExtensionSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountPluginSpec.groovy
Somewhere between Android Studio 3.0 alpha1 and beta6, the AGP API
changed in a few ways.  Notably, the `outputFile` property of variant
outputs is now properly implemented, and the PackageLibraryTask's
archive path now points to an AAR, and not a folder.
We account for both of those changes by updating the modern task such
that it accepts an input file, and not an input directory.
Fixes #217
=> Replace modern 'InputDirectory' with 'InputFile'

src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt, src/main/kotlin/com/getkeepsafe/dexcount/Tasks.kt, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountExtensionSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountPluginSpec.groovy
Hello. 
I try to fix this issue:
https://github.com/KeepSafe/dexcount-gradle-plugin/issues/220
In my project it works. But I not sure for all projects.
=> Fix renaming build output file name after initialize plugin

src/main/java/com/android/dexdeps/DexData.java
Android 8 added another Dex file format version - 038. This fixes the plugin so that an internal check recognises this value as a valid Dex file.
This was tested by running `test.sh` with the integration project's `minSdkVersion` set at 27, with and without the fix.
Fixes #247
=> fix: Support Dex file format version 038

RELEASING.md, build.gradle, gradle/gradle-mvn-push.gradle, gradle/gradle-plugin-portal.gradle
This is broken in that a simple `./gradlew publishPlugins` doesn't do everything it needs to - we need to make gradle sign the binaries separately.  We'll fix that later.
=> Initial config for plugins.gradle.org

.buildscript/test.sh, build.gradle, gradle/dependencies.gradle, integration/app/build.gradle, integration/lib/build.gradle, integration/tests/build.gradle, src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
The main change here is the addition of the 'ThreeThreeProvider' class, which configures the method-count tasks in the presence of AGP 3.3+.  All the rest of the changes account for build errors due to updating to AGP 3.3, and the changes entailed by fixing those errors.
Fixes #259
=> Avoid using deprecated ApkVariant methods in AGP 3.3+

.buildscript/test.sh, gradle/dependencies.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
Although it itself isn't marked deprecated, The internal implementation uses deprecated methods; if not de jure, it is de facto deprecated.
It appears that the only supported way to get the path of an output file is to construct it yourself; we'll do that here, and add checks to the integration test suite to catch any future deprecations.
Fixes #263
=> Stop using ApkVariant#getOutputFile()

README.md, build.gradle, gradle/dependencies.gradle, integration/java-app/build.gradle, integration/java-app/src/main/java/com/getkeepsafe/dexcount/integration/SomeClass.java, integration/java-app/src/test/java/com/getkeepsafe/dexcount/integration/ExampleUnitTest.java, integration/java-library/build.gradle, integration/java-library/src/main/java/com/getkeepsafe/dexcount/integration/SomeClass.java, integration/java-library/src/test/java/com/getkeepsafe/dexcount/integration/ExampleUnitTest.java, integration/settings.gradle, src/main/kotlin/com/getkeepsafe/dexcount/DexMethodCountExtension.kt, src/main/kotlin/com/getkeepsafe/dexcount/PackageTree.kt, src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt, src/main/kotlin/com/getkeepsafe/dexcount/PrintOptions.kt, src/main/kotlin/com/getkeepsafe/dexcount/SourceFile.kt, src/main/kotlin/com/getkeepsafe/dexcount/Tasks.kt, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountExtensionSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountPluginSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/JarFileSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/PackageTreeSpec.groovy
I broke down the PR into smaller commits. It might be easier to review them individually. This PR resolves #270. 
Overall this PR adds one new parameter `printDeclarations` to the extension. When turned on the report prints also declared methods in separate columns. This only works for AARs, because I couldn't find a good way to find the `.jar` file for APKs. 
Additionally, I've added support for the `java` and `java-library` plugin. There `printDeclarations` must be turned on and the report only contains the declarations and not references.
=> Count declared methods and fields

.buildscript/test.sh, integration/app/build.gradle, integration/tests/build.gradle, src/main/kotlin/com/getkeepsafe/dexcount/DexCountTask.kt, src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt, src/test/groovy/com/getkeepsafe/dexcount/DexCountExtensionSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountPluginSpec.groovy
I forgot one input that should be a property.
Realized that I don't need to inject `ObjectFactory` because tasks have a property reference.
Realized that I could use `ConfigurableFileColllection` instead of `Provider<FileCollection>`.
Realized that we weren't minifying in integration tests, and we should.
=> Better property API usage, also minify in integration tests

.buildscript/test.sh, integration/app/build.gradle, src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
Release 1.0.0 broke counting of renamed APKs.
In a nutshell this is because of the way Gradle's `DomainObjectCollection<T>#all` method works.  Callbacks given to `all` are executed in the order received, and as a plugin we typically run before the users' `android` blocks are configured.
In 1.0.0, we made a number of changes and inadvertently made configuration of output file names eager, where they had been lazy.  This meant that since we ran before user callbacks, we never saw the renamed APK.
Fixed here by deferring constructing the APK path until the counting task actually runs.
Fixes #291
=> Allow counting of renamed output files

src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
The initial fix for handling renamed APKs inadvertently used an API introduced in Gradle 6.0, breaking our commitment to supporting Gradle 5.1 and above.
There's a less-obvious way to get a `Provider<RegularFile>` via `ProjectLayout`, and that has apparently been available since 4.3.  We'll use that here instead.
Fixes #291
=> Use ProjectLayout to get a Provider<RegularFile>

src/main/kotlin/com/getkeepsafe/dexcount/DexCountTask.kt
As of Gradle 6.5, referencing a task's `Project` during execution will invalidate the configuration cache and possibly be flagged as a build error: https://docs.gradle.org/6.5-rc-1/userguide/configuration_cache.html#use_project_during_execution
I don't _believe_ that our current uses of `project` are execution-time, but with this PR we won't have to wonder - we'll just use an injected `ObjectFactory` service instead.
=> Don't use getProject() in DexCountTask

.buildscript/test.sh, gradle/dependencies.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/kotlin/com/getkeepsafe/dexcount/DexCountTask.kt, src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountPluginSpec.groovy
Fixes #298, mostly
This PR fixes two bugs:
1) MissingValueException when trying to read proguard mapping files on builds without obfuscation
2) `IllegalStateException: Extension not initialized yet, couldn't access compileSdkVersion.`
We fix 1 by just disabling deobfuscation.  The API for accessing mapping files is simply broken (see https://issuetracker.google.com/u/1/issues/158379522).
Number 2 is fixed by deferring looking up SDK location until the `afterEvaluate` phase, when whatever internal state is necessary has been set up.
=> Fix for AGP 4.1 betas

.buildscript/test.sh, .gitignore, gradle.properties, gradle/dependencies.gradle, integration/app/CMakeLists.txt, integration/app/build.gradle, integration/app/src/main/cpp/lib.cpp, integration/app/src/main/java/com/getkeepsafe/dexcount/integration/MainActivity.java, integration/lib/build.gradle, src/main/kotlin/com/getkeepsafe/dexcount/ColorConsole.kt, src/main/kotlin/com/getkeepsafe/dexcount/CountReporter.kt, src/main/kotlin/com/getkeepsafe/dexcount/DexCountTask.kt, src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt, src/test/groovy/com/getkeepsafe/dexcount/DexCountExtensionSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountPluginSpec.groovy
This absurdly-large PR adds essentially a brand-new plugin implementation using the new APIs introduced in AGP 4.1.0.  For various reasons this requires breaking back-compat in terms of the names and locations of output files on older AGP versions.  (tl;dr: not possible to replicate the exact layout in the new API, and it's better to have a consistent format rather than vary it based on AGP version).
Fixes #301
=> Add AGP 4.1 support

.buildscript/test.sh, src/main/kotlin/com/getkeepsafe/dexcount/DexCountTask.kt, src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt, src/main/kotlin/com/getkeepsafe/dexcount/SourceFile.kt
This PR adds a new task `count<Variant>BundleDexMethods` in projects using AGP 4.1.0+.  It also opens the _possibility_ of supporting .aab counting in earlier versions, since all that we really needed was a tweak in the regex for extracting .dex files from zip archives.  TBD on whether I actually get around to "backporting" AAB support.
Fixes #250
=> Add support for counting app bundles

src/main/kotlin/com/getkeepsafe/dexcount/SourceFile.kt
This is such a hack, but then so is AAR method counting so whatevs
Fixes #310
=> Detect AAR minSdkVersion and pass it to dx

src/main/kotlin/com/getkeepsafe/dexcount/CountReporter.kt, src/main/kotlin/com/getkeepsafe/dexcount/GeneratePackageTreeTask.kt, src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt, src/test/groovy/com/getkeepsafe/dexcount/DexCountExtensionSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountPluginSpec.groovy
- Make all instantiations of `PrintOptions` in the plugin use the new factory extension function on `DexCountExtension`.
- Rename `BaseGeneratePackageTreeTask#variantNameProperty` -> `outputFileNameProperty`, because
a) that's all the property is used for
b) jars don't have variants
- Provide `outputFileNameProperty` values for jar-counting tasks derived from the counted jar's filename.
- Use a Gradle Provider for getting Deobfuscators rather than a kotlin lazy val; this ought to be slightly more future-proof against lifecycle bugs, since in theory it should respond to the underlying property providing the mapping file.
- Document at least the base task's inputs and outputs.
=> Various small cleanups and refactorings following the big split

src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
We have a minimum AGP requirement of 3.4.0, so it makes no sense to have code in the plugin to handle earlier versions.  Also, I discovered a bug in ThreeFourApplicator.Factory#minimumRevision; it erroneously was copy/pasted as "4.1.0".  Fixed here.
=> Remove ThreeOhApplicator, rename ThreeThree to ThreeFour

build.gradle, src/test/groovy/com/getkeepsafe/dexcount/DeobfuscatorSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/DexCountExtensionSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/DexFileSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountPluginSpec.groovy, src/test/groovy/com/getkeepsafe/dexcount/JarFileSpec.groovy
May as well give it a shot.
This upgrade does kind of suck because it renders JUnit's TemporaryFolder rule useless, and the Spock-native replacement is yet to be merged.
=> Upgrade to Spock 2.0-M3

build.gradle, src/main/kotlin/com/getkeepsafe/dexcount/GeneratePackageTreeTask.kt, src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt, src/main/kotlin/com/getkeepsafe/dexcount/SourceFile.kt, src/test/groovy/com/getkeepsafe/dexcount/DexFileSpec.groovy
Nobody has _asked_ for this but I can't help but think that it's safer to rely on the same build-tools version for _counting_ AARs as the one used to _build_ it.  Now that I know that we can, well, here we are.
=> Try to use the same dx version as used in the project being counted

.github/workflows/ci.yml, src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
Our integration tests broke subtly, at some point in the past.  I didn't notice because our github action cached the Gradle build-cache folders in each individual integration-test, so the expected APK files were still there, despite the tasks that produce them never running.
In fact, I only noticed when switching to a new _laptop_ where I also didn't have the build-cache folders handy.
This PR fixes both the dependency problem, and the CI problem - no more caching anything to do with integration tests.
It also removes a dead function.
(fyi @ZacSweers, since you inquired privately)
=> Fix broken task-dependency chain under AGP < 3.6

src/main/kotlin/com/getkeepsafe/dexcount/DexCountOutputTask.kt, src/main/kotlin/com/getkeepsafe/dexcount/GeneratePackageTreeTask.kt, src/main/kotlin/com/getkeepsafe/dexcount/Thrifty.kt
This PR streamlines the reading and writing of intermediate thrift data, allowing the possibility of streaming data to/from disk using the Okio source/sink APIs instead of reading the whole shebang into memory at once, then writing it.
=> Be more efficient when reading/writing thrift treegen data

docs/ci.md
The `.csv` file is actually saved in another directory which is `app/build/outputs/dexcount/$variant/summary.csv`
=> Fix path to the .csv summary file in CI documentation

build.gradle, src/main/kotlin/com/getkeepsafe/dexcount/GeneratePackageTreeTask.kt, src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
Now with AGP 4.2, we can finally use the missing-in-action `ArtifactType.AAR`.  In our 4.1 implementation, we had to fish out a `BundleAar` task by name to get a handle on the AAR itself, which is inherently unstable, and also we had to use an `afterEvaluate` block which is _also_ unstable.
Now that 4.2 is here we can actually "color in the lines" so to speak and rely on the official AGP API.
=> Use ArtifactType.AAR in AGP 4.2+ instead of gross hack

build.gradle, src/main/kotlin/com/getkeepsafe/dexcount/Deobfuscator.kt, src/main/kotlin/com/getkeepsafe/dexcount/DexCountExtension.kt, src/main/kotlin/com/getkeepsafe/dexcount/SourceFile.kt
- Remove deprecated/unused bits of `DexCountExtension`
- Clean up `Deobfuscator` implementation
- Fix leftover JavaDoc syntax in SourceFile.kt
=> Miscellaneous acts of tidiness

build.gradle, src/integrationTest/groovy/com/getkeepsafe/dexcount/IntegrationSpec.groovy, src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
There was some unfortunate API breakage in beta04 and alpha03, respectively, around the packaging of `ApplicationAndroidComponentsExtension` and friends.  In the newer alpha in particular, the old versions of these classes are just gone.
7.0.0-beta05 restored the deprecated classes, at least, and so we can support it with little effort.  7.1.0 support now seems like a bigger task, likely requiring rewriting 4.2.0 to use reflection.  Because the work involved is not yet clear, I'm calling 7.1.0 "unsupported" for the time being.  When we get closer to a 7.1.0 release, we'll support it properly.
=> Add support for AGP 7.0.0-beta05, withdraw support for 7.1.0-alpha02

src/integrationTest/groovy/com/getkeepsafe/dexcount/IntegrationSpec.groovy
We use `AntBuilder` in integration tests to recursively copy directories.  It's deprecated, but until the move to Java (and the adoption of Commons IO as a dependency) we didn't have a graceful alternative.  Now we do, and can remove this lurking landmine from our code.
=> Use Commons IO instead of deprecated AntBuilder to copy directories

src/main/java/com/getkeepsafe/dexcount/DexCountExtension.java
In the new `DexCountExtension` implementation, we have a bunch of property fields `foo` and expose accessors `getFoo()`.  The fields are private.  Gradle, in its Groovy flavor, generates field-like accessors for these properties so one can write
```groovy
dexcount {
foo = "bar"
}
```  
and it's the same as if one had written
```groovy
dexcount {
getfoo().set("bar")
}
```
Evidently, IntelliJ is not smart enough to realize this because it warns that the former code sample "access to 'foo' exceeds its rights".  Its analyzer doesn't know that `foo` is actually a generated accessor.
We could (and probably should) report this to JetBrains, but in the meantime, we can just rename the fields to shut it up.
Note that this is a cosmetic problem/solution only - actual builds work just fine.
Fixes …
=> Ensure extension field names don't clash with generated accessors

src/integrationTest/groovy/com/getkeepsafe/dexcount/IntegrationSpec.groovy, src/main/java/com/getkeepsafe/dexcount/plugin/AbstractLegacyTaskApplicator.java, src/main/java/com/getkeepsafe/dexcount/treegen/workers/BaseWorker.java
On Gradle 6.1.1, `getParameters().getOutputDirectory().file("summary.csv")` was failing with an error about not being able to make an absolute path from `"summary.csv"`.  Debugging confirms that we do in fact have an absolute project path stuffed into those parameters, and I'm not clear on why this error happens.  It definitely works correctly in Gradle 6.5 and later.
Working around the bug by using the `File(File, String)` constructor instead.
Also fixing one missed Kotlin string interpolation that I missed in the earlier migration.
Fixes #410
=> Work around apparent bug in Gradle 6.1 DirectoryProperty#file

build.gradle
Had a problem running 'build' task for the project. The problem was in 'Javadoc' task, so I added 'source' in the configuration of the task and changed links to 'https' instead of 'http'.
=> Fix a problem with 'Javadoc' task

build.gradle, src/integrationTest/groovy/com/getkeepsafe/dexcount/IntegrationSpec.groovy, src/main/java/com/getkeepsafe/dexcount/plugin/FourTwoApplicator.java
Wherein AGP has finally removed some deprecated classes we relied on for 4.2.0 support.
Time to bust out Ye Olde Reflection.
=> Support AGP 7.2.0-alpha05

build.gradle, gradle/libs.versions.toml
This chore will hopefully make the (complex) way we consume dependencies a little more legible.
=> Start using a version catalog, organize + document dependencies

build.gradle
`compileOnly` is clear about _what_ it does but not _why_, and for us the "why" is important.  This PR adds two new Gradle configurations - `androidBuildTool` and `workerImplementation`.  The former is (hopefully) clear about the fact that its dependencies are expected to come from projects consuming this plugin.  The latter is certainly more clear about the fact that its dependencies are destined for isolated Gradle Workers.
This also lets us clean up the dependency-list task, making future maintenance a bit simpler.
=> Use custom configurations to clarify dependency types

gradle.properties
Apparently in future releases, they won't publish to Sonatype Nexus automatically; some extra configuration is required.  Ditto for signing releases.
Done here, to silence warnings.
=> gradle-maven-publish-plugin requires new config for Maven Central

gradle/libs.versions.toml, src/integrationTest/groovy/com/getkeepsafe/dexcount/IntegrationSpec.groovy, src/integrationTest/projects/integration/app/build.gradle, src/integrationTest/projects/integration/lib/build.gradle, src/integrationTest/projects/integration/tests/build.gradle
This is the first AGP version to require `android.namespace` over package names in AndroidManifest.xml; the test projects have to do this in a try/ignore block and continue to use AndroidManifest.xml.
Something in R8 (I think?) has changed since 8.0.0-alpha01, and the test project fails to build with errors about missing support-annotation classes.  I don't really get that - they're source-only retention - but sure enough, we'd excluded them at some point in the past from the test project.  Likely it was for AGP versions older than 3.4.0, our minimum supported version.
Un-excluding them fixes the build, but changes the counts for many (but not all) of the test-project builds.
=> Support AGP 8.0.0-alpha03

docs/config.md
fixes #493
- Replace the samples with current format, e.g. OutputFormat.LIST.
- add `import com.getkeepsafe.dexcount.OutputFormat` for the output attribute
=> document the current OutputFormat configuration

gradle/libs.versions.toml
This change ensures that our code continues to build and function with newer versions of R8.  Because this tool is provided by AGP, the version we build with has no impact on projects that use dexcount.
=> Bump R8 to 4.0.48

build.gradle, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, src/integrationTest/groovy/com/getkeepsafe/dexcount/IntegrationSpec.groovy
Due to an [AGP issue](https://issuetracker.google.com/issues/265809620), and the fact that both AGP previews we build and test against don't have the related fix, we have to update our Gradle version and our AGP previews in tandem.  This is a larger PR than usual as a result, but thankfully is otherwise without totally routine.
=> Bump Gradle, AGP 8.0.0 and 8.1.0 previews

.github/workflows/ci.yml
- Updates actions.
- Use `gradle-build-action` to cache Gradle and speed up builds.
- Let CI run for more PRs and branches.
=> Polish GHA config
