- .travis.yml
- CHANGELOG.md
- gradle.properties
- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountExtension.groovy
Doesn't hurt, but is change to the default public contract.
> Enable field counts by default

- README.md
- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountExtension.groovy
- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
- src/main/groovy/com/getkeepsafe/dexcount/PackageTree.groovy
- src/main/groovy/com/getkeepsafe/dexcount/PrintOptions.groovy
- src/test/groovy/com/getkeepsafe/dexcount/PackageTreeTest.groovy
This option should be quite useful; currently there is no way to determine the total number of methods, other than parsing the build logs.
I am open for suggestions if you think it should be done another way :)
> Added the `includeTotalMethodCount` option

- CHANGELOG.md
- README.md
- gradle.properties
> Prepare next development version

- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
> Fix percentage-used MethodNotFound and output

- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
> Don't display negative remaining totals for multidexed builds

- README.md
> Add documentation for maxTreeDepth

- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
My mistake :sweat_smile: 
Copy-paste is evil power :smile:
> Fix field count in integration with TeamCity

- src/main/groovy/com/getkeepsafe/dexcount/sdkresolver/SdkResolver.groovy
> Legal: Unescape license url

- integration/app/build.gradle
- integration/settings.gradle
- integration/tests/build.gradle
- integration/tests/src/main/AndroidManifest.xml
- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy
- test.sh
> Add support for Android test modules

- src/main/groovy/com/getkeepsafe/dexcount/DexCountException.groovy
- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
- src/test/groovy/com/getkeepsafe/dexcount/DexCountExceptionTest.groovy
> Fix crash when logging exceptions

- src/main/groovy/com/getkeepsafe/dexcount/PackageTree.groovy
`DefaultGroovyMethods#each(Collection, Closure)` does not exist in
older versions of Groovy that are bundled in old versions of Gradle;
this causes crashes in projects that use those Gradle versions and this
plugin.  To work around, this adds our own copy of `each`.
Fixes #108.
> Replace usage of DefaultGroovyMethods#each with custom helper

- README.md
- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountExtension.groovy
- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy
> Don't count Instant Run builds by default

- src/main/groovy/com/getkeepsafe/dexcount/DexFile.groovy
Fixes #121; hopefully the last time we'll fix a Java 7 compatibility issue.
> Remove dependency on JDK-8-only Process methods.

- README.md
- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountExtension.groovy
- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
@benjamin-bader Solves #146
Add max method count, fails build when the apk/aar goes over specified max
> Feature - Add max method count

- src/main/groovy/com/getkeepsafe/dexcount/Deobfuscator.groovy
- src/main/groovy/com/getkeepsafe/dexcount/DexCountException.groovy
- src/main/groovy/com/getkeepsafe/dexcount/DexFile.groovy
- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountExtension.groovy
- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy
- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
- src/main/groovy/com/getkeepsafe/dexcount/GradleApi.groovy
- src/main/groovy/com/getkeepsafe/dexcount/IOUtil.groovy
- src/main/groovy/com/getkeepsafe/dexcount/OutputFormat.groovy
- src/main/groovy/com/getkeepsafe/dexcount/PackageTree.groovy
- src/main/groovy/com/getkeepsafe/dexcount/PrintOptions.groovy
- src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountPluginSpec.groovy
- src/test/groovy/com/getkeepsafe/dexcount/RefHelpers.groovy
- Cleaning up `Groovy` code
- `void` -> `def`
- remove semicolons
- remove extra modifiers
- added documentation to the extension class, more to come
- Added tests
- added tests to the plugin class, more to come
> Clean up Groovy + Add more tests

- build.gradle
- gradle/gradle-mvn-push.gradle
Keep maven plugin related code in the maven script. @benjamin-bader
> Move artifacts to maven script

- src/main/groovy/com/getkeepsafe/dexcount/DexFile.groovy
The current Dexcount Gradle plugin leaves the apk file handles open. On windows machines this results in a locked apk file for the rest of the build meaning no other task can get write access.
Surprisingly the java.util.zip.ZipFile opens the file in a constructor so I wrapped the code needing access to the ZipFile into withCloseable which makes sure that the file handle gets closed.
Additionally I made sure there are no other file leaks by using [file leak detector](http://file-leak-detector.kohsuke.org/) and adding the following to integration/gradle.properties: `org.gradle.jvmargs=-javaagent:/tmp/file-leak-detector.jar=http=19999`.
> Make sure ZipFile instances are closed

- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy
> Remove use of uncapitalize() to fix users of Gradle < 3.5

- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountPlugin.groovy
> Create dexcount extension before doing instant-run check

- build.gradle
- integration/app/build.gradle
- integration/build.gradle
- integration/settings.gradle
- integration/tests/build.gradle
- settings.gradle
@benjamin-bader This was from this PR: https://github.com/KeepSafe/dexcount-gradle-plugin/pull/157.
I am going to finish it by breaking it into smaller chunks.
> [Gradle] - Use double quotes for consistency through out the project

- build.gradle
PR https://github.com/KeepSafe/dexcount-gradle-plugin/pull/195 needs to be merged first.
> [Gradle] - Add Kotlin support

- .travis.yml
@benjamin-bader Applying fix told to me by the TravisCI people: https://github.com/travis-ci/travis-ci/issues/8123#issuecomment-316466355.
> [Gradle] - Use android block for the sdk + fix build

- .editorconfig
- build.gradle
- gradle/compile.gradle
- gradle/versions.gradle
- Turn off annoying Javadoc lint
- Turn Java warnings into errors
- Turn Groovy warnings into errors
> [Gradle] - Turn off java doc lint, turn java and groovy warnings to errors

- .travis.yml
- build.gradle
- gradle/versions.gradle
- integration/tests/build.gradle
- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountExtension.groovy
- src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountTask.groovy
- src/main/groovy/com/getkeepsafe/dexcount/sdkresolver/SdkResolver.groovy
- src/main/groovy/com/getkeepsafe/dexcount/sdkresolver/System.groovy
- src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountExtensionSpec.groovy
- src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountPluginSpec.groovy
- Upgraded dependencies
- Updated to use new Java plugin from Gradle
- Removed left over semi-colons from `.groovy` files
- For some reason, when upgrading the Android Gradle plugin, I cannot seem to use "apply" for the tests
> [Gradle] - Update dependencies

- .buildscript/test.sh
- .travis.yml
- gradle/versions.gradle
Taken from: https://github.com/JakeWharton/butterknife/blob/master/.travis.yml#L14
> [Build] - Update build tools and ci

- src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
The move from Groovy to Kotlin has broken dexcount for AGP versions
below 3.0, because the return type of `BaseVariant#getOutputs()`
changed at version 3.0 from a simple List to a DomainObjectCollection.
This breaks method resolution, which in Kotlin is strict.
Fixed here by using reflection in the legacy provider.
> Get variant outputs reflectively for AGP 2.X

- .travis.yml
Hopefully this will unblock two current PRs (not naming them because I don't want Github to automatically close them!).
> Add new Android SDK license hash to Travis build

- .buildscript/test.sh
- gradle/versions.gradle
- src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
- src/main/kotlin/com/getkeepsafe/dexcount/Tasks.kt
Closes https://github.com/KeepSafe/dexcount-gradle-plugin/issues/224
We need https://github.com/KeepSafe/dexcount-gradle-plugin/pull/226 merged first
> Add support for 3.1.0-alpha01

- .travis.yml
- gradle/versions.gradle
> update build tools, update kotlin

- gradle/dependencies.gradle
- gradle/wrapper/gradle-wrapper.properties
@jaredsburrows See anything objectionable here?
> Update Kotlin and AGP versions

- src/main/kotlin/com/getkeepsafe/dexcount/DexMethodCountExtension.kt
Mirros, what I've got in my Plugin. https://github.com/vanniktech/gradle-android-apk-size-plugin/pull/87
> Turn Teamcity Integration on by default if running on Teamcity.

- CHANGELOG.md
- README.md
- src/main/kotlin/com/getkeepsafe/dexcount/DexMethodCountExtension.kt
- src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
- src/main/kotlin/com/getkeepsafe/dexcount/Tasks.kt
- src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountPluginSpec.groovy
> Add configuration to dynamically disable plugin

- README.md
Fixes #258 
These instructions are *untested by me*, but are taken verbatim from #256.  I'll leave this open for a while, in case anyone has corrections.
> Update README.md with .kts instructions

- .travis.yml
- build.gradle
- src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountExtensionSpec.groovy
- src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountPluginSpec.groovy
- src/test/groovy/com/getkeepsafe/dexcount/PackageTreeSpec.groovy
- src/test/groovy/com/getkeepsafe/dexcount/RefHelpers.groovy
Migrate tests to https://docs.gradle.org/current/userguide/test_kit.html
> Update Tests to new testing strategy

- src/main/java/com/android/dexdeps/DexData.java
> Add dex v39 magic header constant

- src/main/kotlin/com/getkeepsafe/dexcount/GradleApi.kt
- src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
- src/test/groovy/com/getkeepsafe/dexcount/GradleVersionSpec.groovy
> Require Gradle 5.1

- integration/app/build.gradle
- integration/java-app/build.gradle
- integration/java-library/build.gradle
- integration/lib/build.gradle
- integration/tests/build.gradle
- src/main/kotlin/com/getkeepsafe/dexcount/Deobfuscator.kt
- src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
- src/main/kotlin/com/getkeepsafe/dexcount/Tasks.kt
> Mapping file provider

- src/main/kotlin/com/getkeepsafe/dexcount/DexCountExtension.kt
- src/main/kotlin/com/getkeepsafe/dexcount/DexCountTask.kt
- src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
- src/test/groovy/com/getkeepsafe/dexcount/DexCountExtensionSpec.groovy
- src/test/groovy/com/getkeepsafe/dexcount/DexMethodCountPluginSpec.groovy
> Drop support for AGP 2.x

- src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
> Be a bit lazier in accessing variant output properties

- src/main/kotlin/com/getkeepsafe/dexcount/GradleApi.kt
- src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
> Remove GradleApi hacks

- build.gradle
- gradle/dependencies.gradle
- src/main/kotlin/com/getkeepsafe/dexcount/PackageTree.kt
- src/main/thrift/PackageTree.thrift
- src/test/groovy/com/getkeepsafe/dexcount/PackageTreeSpec.groovy
> Add Thrift model for PackageTree serialization

- src/main/kotlin/com/getkeepsafe/dexcount/DexCountOutputTask.kt
- src/main/kotlin/com/getkeepsafe/dexcount/GeneratePackageTreeTask.kt
- src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
> Gzip TreeGenOutput file on disk

- src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
Partially addresses #330 but we still need to document this prior to release.
> Skip plugin application if 0 < AGP version < 3.4.0

- src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
> Don't eagerly resolve all package tasks

- build.gradle
- src/integrationTest/groovy/com/getkeepsafe/dexcount/IntegrationSpec.groovy
This was cake.  Let's hope it holds through the remaining alphas and betas!
> Add support for AGP 7.1.0-alpha02

- src/main/java/com/getkeepsafe/dexcount/Deobfuscator.java
- src/main/java/com/getkeepsafe/dexcount/OutputFormat.java
> Move OutputFormat to Java

- src/main/java/com/getkeepsafe/dexcount/DexMethodCountPlugin.java
- src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt
> Move DexMethodCountPlugin to Java

- .github/workflows/ci.yml
- build.gradle
- gradle.properties
- src/integrationTest/groovy/com/getkeepsafe/dexcount/IntegrationSpec.groovy
- src/integrationTest/projects/integration/build.gradle
- src/main/java/com/getkeepsafe/dexcount/plugin/AbstractLegacyTaskApplicator.java
- src/main/java/com/getkeepsafe/dexcount/plugin/FourOneApplicator.java
- src/main/java/com/getkeepsafe/dexcount/plugin/FourTwoApplicator.java
- src/main/java/com/getkeepsafe/dexcount/treegen/workers/BaseWorker.java
I can't believe I almost released something this broken.  Integration tests were passing for the last dozen commits only due to cached older builds, I believe.  Bumping to a new snapshot version exposed how very broken things are.
Anyhow, this PR seems to fix everything I found to be broken.
> Fix AGP 4.2 and below

- build.gradle
- src/integrationTest/groovy/com/getkeepsafe/dexcount/IntegrationSpec.groovy
I'm flabbergasted.  Not a single line of actual code had to change!  I can't remember a single minor-version release where I didn't have to change something, ever.  Bravo, Team AGP!
> Support AGP 7.3.0-alpha01

- gradle/libs.versions.toml
Support for Java 17+ bytecodes
> r8 4.0.48 -> 8.1.56
